version: '3.8'
services:
  vproapp:
    build: ./Docker-files/app
    container_name: vproapp
    image: ceto1104/vprofileapp
    volumes:
      - vproappdata:/usr/local/tomcat/webapps 
    ports:
    - "8080:8080"
  vprodb:
    build: ./Docker-files/db
    image: ceto1104/vprofiledb
    container_name: vprodb
    ports:
    - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
  vproweb:
    container_name: vproweb
    build: ./Docker-files/web
    image: ceto1104/vprofileweb
    ports:
    - "80:80"
  vprocache01:
    container_name: vprocache01
    image: memcached
    ports:
    - "11211:11211"
  vpromq01:
    container_name: vpromq01
    image: rabbitmq
    ports:
    - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest 
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
    vprodbdata: {}
    vproappdata: {}